### ISSUE TITLE
RNInstallReferrerClient.java Fatal Exception: java.lang.SecurityException Not allowed to bind to service Intent 

### ISSUE THREAD

**Issue by karthikpala** [react-native-community/react-native-device-info#1037]
# Bug report

## Summary

I am seeing many crash reports in firebase crashlytics with the below stack trace. I am unable to replicate this in any of my local devices

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 455.73 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 17, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2
```

Library version: 5.5.6

## Steps to reproduce

I am unable to replicate the below issue in my local test device

```bash
Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.finsky.BIND_GET_INSTALL_REFERRER_SERVICE cmp=com.android.vending/com.google.android.finsky.externalreferrer.GetInstallReferrerService }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1497)
       at android.app.ContextImpl.bindService(ContextImpl.java:1451)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
       at com.android.installreferrer.api.InstallReferrerClientImpl.startConnection(InstallReferrerClientImpl.java:38)
       at com.learnium.RNDeviceInfo.RNInstallReferrerClient.<init>(RNInstallReferrerClient.java:20)
       at com.learnium.RNDeviceInfo.RNDeviceModule.<init>(RNDeviceModule.java:83)
       at com.learnium.RNDeviceInfo.RNDeviceInfo.createNativeModules(RNDeviceInfo.java:23)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
       at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
       at java.lang.Thread.run(Thread.java:761)
```

Describe what you expected to happen:

App should not be crashed in production

**Comment by mikehardy** [comment]
I suspect your build process somehow included a stale version. v5.6.1 should not be able to throw that stack trace as it is a "try" statement, not a call to the underlying API method mentioned, and the try statement has a catch of Exception, so SecurityException would be caught and logged and not cause a crash.

https://github.com/react-native-community/react-native-device-info/blob/1e095ec868707a47c5b43995d8fab82ce71d1769/android/src/main/java/com/learnium/RNDeviceInfo/RNInstallReferrerClient.java#L20-L26

**Comment by mikehardy** [comment]
No response from submitter

**Comment by karthikpala** [comment]
@mikehardy Sorry I forgot to reply. We have updated to the latest version of device info library and we will let you know if we still see this issue. Thanks for your support
