### ISSUE TITLE
Crashing from getInstallReferrer() when app doesn't use the function

### ISSUE THREAD

**Issue by winardis** [react-native-community/react-native-device-info#1051]
# Bug report
Hi so recently i just uploaded an new update of the app i'm working on with these env
react-native 0.62.2
react-native-device-info 5.5.7

but i received error reports from Sentry that 22 events from 14 users with the following message :
Service not connected. Please start a connection before using the service.

`
java.lang.IllegalStateException: Service not connected. Please start a connection before using the service.
    at com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer(InstallReferrerClientImpl.java:8)
    at com.learnium.RNDeviceInfo.RNInstallReferrerClient$1.onInstallReferrerSetupFinished(RNInstallReferrerClient.java:47)
    at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:7)
    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2067)
    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2099)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:228)
    at android.app.ActivityThread.main(ActivityThread.java:7782)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
`

The issue i'm facing here is i'm not using the feature getInstallReferrer();

Here are the functions that i use from RN Device Info : 
const appVersion = DeviceInfo.getVersion();
const buildNumber = DeviceInfo.getBuildNumber();
const isTablet = DeviceInfo.isTablet();

is the function getInstallReferrer() will always trigger either we use it or not?

**Comment by mikehardy** [comment]
I believe this is a dupe https://github.com/react-native-community/react-native-device-info/issues/975

I do not believe it is possible with current code, you may inspect it for yourself, it catches every exception in that area, including the one you mention

It should not be possible, you probably have something stale in your build

perhaps `npx react-native-clean-project`

If you can reproduce it in a clean project (perhaps the example) we may investigate further
