### ISSUE TITLE
java.lang.NoSuchFieldError: No static field PREVIEW_SDK_INT

### ISSUE THREAD

**Issue by xnmalex** [react-native-community/react-native-device-info#716]
## Summary

|             |     |
| ----------- | --- |
| Version     | 2.2.2   |
| Affected OS | Android  |
| OS Version  | 5.1   |

## Current behavior

Crash 
java.lang.NoSuchFieldError: No static field PREVIEW_SDK_INT of type I in class Landroid/os/Build$VERSION; or its superclasses (declaration of 'android.os.Build$VERSION' appears in /system/framework/framework.jar:classes2.dex)
        at com.learnium.RNDeviceInfo.RNDeviceModule.generateConstants(RNDeviceModule.java:511)
        at com.learnium.RNDeviceInfo.RNDeviceModule.<init>(RNDeviceModule.java:84)
        at com.learnium.RNDeviceInfo.RNDeviceInfo.createNativeModules(RNDeviceInfo.java:28)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1212)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1182)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1120)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
        at java.lang.Thread.run(Thread.java:818)

## Expected behavior

No Crash

**Comment by xnmalex** [comment]
related to #715

**Comment by mikehardy** [comment]
Thanks! I merged this and released 2.2.2 from a tiny Bolivian airport ;-) - as mentioned in the release note: 


Sorry for all affected! I'm traveling right now and it is difficult for me to quality control things well, while we don't have great CI support

PRs that add CirlceCI support for this repo, ideally using the react-native-community CircleCI orb (read as: most of the work should be done for you) would be most welcome!
