### ISSUE TITLE
java.lang.InternalError: Invoking set with bad arg 0, type 'Ljava/lang/String;' not instance of 'Landroidx/core/content/res/FontResourcesParserCompat;'

### ISSUE THREAD

**Issue by shoufu** [react-native-community/react-native-device-info#952]
app crash

java.lang.InternalError: Invoking set with bad arg 0, type 'Ljava/lang/String;' not instance of 'Landroidx/core/content/res/FontResourcesParserCompat;'
        at com.learnium.RNDeviceInfo.RNDeviceModule.sendEvent(RNDeviceModule.java:840)
        at com.learnium.RNDeviceInfo.RNDeviceModule.access$500(RNDeviceModule.java:65)
        at com.learnium.RNDeviceInfo.RNDeviceModule$1.onReceive(RNDeviceModule.java:109)
        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

Environment info
"react-native": "^0.61.1",
"react-native-device-info": "^5.5.1",

React native info output:
None

**Comment by mikehardy** [comment]
Very strange - thanks for posting this @shoufu 

There are only 3 usages of that private method in the code:

```
Method
sendEvent(ReactContext, String, Object)
Found usages
Unclassified usage
android
com.learnium.RNDeviceInfo
RNDeviceModule
initialize()
          sendEvent(getReactApplicationContext(), "RNDeviceInfo_powerStateDidChange", batteryState);
            sendEvent(getReactApplicationContext(), "RNDeviceInfo_batteryLevelDidChange", batteryLevel);
            sendEvent(getReactApplicationContext(), "RNDeviceInfo_batteryLevelIsLow", batteryLevel);
```

Each time they are called with a String or Double. The stack frame you reference is:

```java
        Double batteryLevel = powerState.getDouble(BATTERY_LEVEL);
        if(mLastBatteryLevel != batteryLevel) {
            sendEvent(getReactApplicationContext(), "RNDeviceInfo_batteryLevelDidChange", batteryLevel);
```

Which is calling it with a Double.

So, then it calls:

```java
reactContext
            .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
            .emit(eventName, data);
```

And somehow that JSModule (which should only be a RCTDeviceEventEmitter, which expects a string as arg 0) blows up looking for a font-related object?

That makes no sense

I suspect you have some sort of corrupt state, somehow and an `npx react-native-clean-project clean-project-auto && cd ios && pod install` might clear things out.

Either way I'll need some help to reproduce this as I've never seen it happen before and can't understand how it would be possible 🤔
