### ISSUE TITLE
 java.lang.IllegalArgumentException: Invalid path: /storage/emulated/0

### ISSUE THREAD

**Issue by zhuangzhitu** [react-native-community/react-native-device-info#983]
# Bug

251
03-27 14:23:27.582
12112 12210
WARING
System.err
 java.lang.IllegalArgumentException: Invalid path: /storage/emulated/0
252
03-27 14:23:27.582
12112 12210
WARING
System.err
 	at android.os.StatFs.doStat(StatFs.java:51)
253
03-27 14:23:27.582
12112 12210
WARING
System.err
 	at android.os.StatFs.<init>(StatFs.java:41)
254
03-27 14:23:27.582
12112 12210
WARING
System.err
 	at com.learnium.RNDeviceInfo.RNDeviceModule.getFreeDiskStorage(SourceFile:294)
255
03-27 14:23:27.583
12112 12210
WARING
System.err
 	at com.learnium.RNDeviceInfo.RNDeviceModule.generateConstants(SourceFile:504)
256
03-27 14:23:27.583
12112 12210
WARING
System.err
 	at com.learnium.RNDeviceInfo.RNDeviceModule.access$000(SourceFile:58)
257
03-27 14:23:27.583
12112 12210
WARING
System.err
 	at com.learnium.RNDeviceInfo.RNDeviceModule$1.doInBackground(SourceFile:1078)
258
03-27 14:23:27.583
12112 12210
WARING
System.err
 	at android.os.AsyncTask$2.call(AsyncTask.java:333)

## Environment info

android  9.0

Library version: 2.1.0

## Steps To Reproduce
At present only once, I use the way of register is new RNDeviceInfo (true), I think has the same problem before: https://github.com/react-native-community/react-native-device-info/issues/320

**Comment by mikehardy** [comment]
Current library version, 5.5.3 - please upgrade and we can reopen if you can reproduce with the provided example.
