### ISSUE TITLE
app crash with RN0.62.0

### ISSUE THREAD

**Issue by xuqianjin** [react-native-community/react-native-device-info#990]
# Bug

```
java.lang.InternalError: Invoking upTo with bad arg 1, type 'Ljava/lang/String;' not instance of 'Ljava/text/ParsePosition;'
	at com.learnium.RNDeviceInfo.RNDeviceModule.sendEvent(RNDeviceModule.java:840)
	at com.learnium.RNDeviceInfo.RNDeviceModule.access$500(RNDeviceModule.java:65)
	at com.learnium.RNDeviceInfo.RNDeviceModule$1.onReceive(RNDeviceModule.java:104)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)

```
## Environment info
```
"react": "16.13.1",
"react-native": "0.62.0",
"react-native-device-info": "^5.5.3",
```

**Comment by mikehardy** [comment]
Hi there!
Using the example app (which was just updated to RN0.62 https://github.com/react-native-community/react-native-device-info/commit/2ae00c773067856c813460a8870579b15e3f3684) and the most up to date module version (5.5.4), please reproduce this with the example and detail the steps required so we can find the problem

**Comment by xuqianjin** [comment]
> Hi there!
> Using the example app (which was just updated to RN0.62 [2ae00c7](https://github.com/react-native-community/react-native-device-info/commit/2ae00c773067856c813460a8870579b15e3f3684)) and the most up to date module version (5.5.4), please reproduce this with the example and detail the steps required so we can find the problem

@mikehardy thranks for reply,when i run the example app on  simulator, i got the same error
```
10:20:00.089	AndroidRuntime	FATAL EXCEPTION: main
Process: com.example, PID: 5744
java.lang.InternalError: Invoking <init> with bad arg 0, type 'Ljava/lang/String;' not instance of '[B'
	at com.learnium.RNDeviceInfo.RNDeviceModule.sendEvent(RNDeviceModule.java:840)
	at com.learnium.RNDeviceInfo.RNDeviceModule.access$500(RNDeviceModule.java:65)
	at com.learnium.RNDeviceInfo.RNDeviceModule$1.onReceive(RNDeviceModule.java:104)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
10:20:00.090	ActivityManager	  Force finishing activity com.example/.MainActivity
```

**Comment by mikehardy** [comment]
Any idea what's causing it? PRs happily accepted

**Comment by EmreKorpe** [comment]
Clean Project and Build Project problem solved :)

**Comment by rancpine** [comment]
> here

how do you solve this problem? we've encountered it too.
